# Change these first
owner: TheGallium # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: flapy.xyz
    url: https://flapy.xyz/novasphere

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  theme: light
  introTitle: "Status"
  introMessage: Soyez au courrant du status de la connection avec flapy.xyz
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  url: "URL"
  status: "Status"
  history: "Historique"
  responseTime: "Temps de réponse"
  uptime: "Uptime"
  up: "✅ Opérationnel"
  degraded: "⚠️ Dégradée"
  down: "🟥 En panne"
  responseTimeGraphAlt: "Graph de la latance"
  ms: "ms"
  responseTime: "Temps de réponse"
  responseTimeDay: "Temps de réponse sur 24h"
  responseTimeWeek: "Temps de réponse sur 7j"
  responseTimeMonth: "Temps de réponse sur 30j"
  responseTimeYear: "Temps de réponse sur 1 an"
  uptime: "Uptime depuis toujours"
  uptimeDay: "Uptime sur 24h"
  uptimeWeek: "Uptime sur 7j"
  uptimeMonth: "Uptime sur 30j"
  uptimeYear: "Uptime sur 1 an"
  liveStatus: "Status en direct"
  liveStatusHtmlComment: "<!--status en direct-->"
  allSystemsOperational: "✅ Tout les systèmes sont opérationnels"
  degradedPerformance: "⚠️ Performance dégradée"
  completeOutage: "🟥 Panne complète"
  partialOutage: "🟧 Panne partielle"
  footer: " "


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
